services:
  api:
    build:
      context: ./services
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./services/api:/app
      - ./packages/incidents-analyzer:/packages/incidents-analyzer:ro
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - PASSWORD_RESET_TOKEN_EXPIRE_MINUTES=${PASSWORD_RESET_TOKEN_EXPIRE_MINUTES}
      - RESEND_FROM_EMAIL=${RESEND_FROM_EMAIL}
      - FRONTEND_URL=${FRONTEND_URL}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - nexova-net

  uis:
    build:
      context: ./uis
      dockerfile: Dockerfile
    init: true
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./uis/website/my-app:/app/uis/website
      - /app/uis/website/node_modules
      - ./uis/backoffice:/app/uis/backoffice
      - /app/uis/backoffice/node_modules
      - ./src:/app/src:ro
    environment:
      - BACKEND_API_URL=${BACKEND_API_URL}
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
    networks:
      - nexova-net

networks:
  nexova-net:
    name: nexova-net